name: Test

on:
    pull_request:
      branches: [main]
    push:
      branches: [main]
    workflow_dispatch:

jobs:
    test:
      strategy:
        matrix:
          version: [18, 16]
          platform: [ macos-latest, ubuntu-latest, windows-latest ]
      runs-on: ${{ matrix.platform }}

      steps:
      - if: runner.os != 'Windows'
        uses: GitHubSecurityLab/actions-permissions/monitor@v1
        with:
          config: ${{ vars.PERMISSIONS_CONFIG }}
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
            node-version: ${{ matrix.version }}

      - name: Run Tests
        run: |
          npm install
          npm run test
